# Site settings
title: MagicianYang's Blog
email: miraculousyang@sina.com
description: > # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  MagicianYang's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magicianyang.github.io" # "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: # jekyllrb
github_username:  MagicianYang # jekyll

# Build settings
markdown: kramdown
